//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: modeldata.proto
namespace swellanimations
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Animation")]
  public partial class Animation : global::ProtoBuf.IExtensible
  {
    public Animation() {}
    
    private readonly global::System.Collections.Generic.List<swellanimations.Node> _frames = new global::System.Collections.Generic.List<swellanimations.Node>();
    [global::ProtoBuf.ProtoMember(1, Name=@"frames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<swellanimations.Node> frames
    {
      get { return _frames; }
    }
  
    private readonly global::System.Collections.Generic.List<swellanimations.Vector> _spline = new global::System.Collections.Generic.List<swellanimations.Vector>();
    [global::ProtoBuf.ProtoMember(2, Name=@"spline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<swellanimations.Vector> spline
    {
      get { return _spline; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModelData")]
  public partial class ModelData : global::ProtoBuf.IExtensible
  {
    public ModelData() {}
    
    private swellanimations.Node _model = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"model", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public swellanimations.Node model
    {
      get { return _model; }
      set { _model = value; }
    }
    private swellanimations.Vector _upVector = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"upVector", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public swellanimations.Vector upVector
    {
      get { return _upVector; }
      set { _upVector = value; }
    }
    private readonly global::System.Collections.Generic.List<swellanimations.Vector> _controlPoints = new global::System.Collections.Generic.List<swellanimations.Vector>();
    [global::ProtoBuf.ProtoMember(3, Name=@"controlPoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<swellanimations.Vector> controlPoints
    {
      get { return _controlPoints; }
    }
  
    private readonly global::System.Collections.Generic.List<swellanimations.RotationPoint> _rotationpoints = new global::System.Collections.Generic.List<swellanimations.RotationPoint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"rotationpoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<swellanimations.RotationPoint> rotationpoints
    {
      get { return _rotationpoints; }
    }
  
    private int _numberOfFrames;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"numberOfFrames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int numberOfFrames
    {
      get { return _numberOfFrames; }
      set { _numberOfFrames = value; }
    }
    private readonly global::System.Collections.Generic.List<swellanimations.AnimationLayer> _animationLayers = new global::System.Collections.Generic.List<swellanimations.AnimationLayer>();
    [global::ProtoBuf.ProtoMember(6, Name=@"animationLayers", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<swellanimations.AnimationLayer> animationLayers
    {
      get { return _animationLayers; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Vector")]
  public partial class Vector : global::ProtoBuf.IExtensible
  {
    public Vector() {}
    
    private float _x;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"x", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float x
    {
      get { return _x; }
      set { _x = value; }
    }
    private float _y;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"y", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float y
    {
      get { return _y; }
      set { _y = value; }
    }
    private float _z;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"z", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float z
    {
      get { return _z; }
      set { _z = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Node")]
  public partial class Node : global::ProtoBuf.IExtensible
  {
    public Node() {}
    
    private string _name = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private swellanimations.Vector _position = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public swellanimations.Vector position
    {
      get { return _position; }
      set { _position = value; }
    }
    private swellanimations.Vector _eularAngles = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"eularAngles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public swellanimations.Vector eularAngles
    {
      get { return _eularAngles; }
      set { _eularAngles = value; }
    }
    private readonly global::System.Collections.Generic.List<swellanimations.Node> _children = new global::System.Collections.Generic.List<swellanimations.Node>();
    [global::ProtoBuf.ProtoMember(4, Name=@"children", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<swellanimations.Node> children
    {
      get { return _children; }
    }
  
    private swellanimations.Node _parent = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"parent", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public swellanimations.Node parent
    {
      get { return _parent; }
      set { _parent = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RotationPoint")]
  public partial class RotationPoint : global::ProtoBuf.IExtensible
  {
    public RotationPoint() {}
    
    private swellanimations.Vector _Rotation;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Rotation", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public swellanimations.Vector Rotation
    {
      get { return _Rotation; }
      set { _Rotation = value; }
    }
    private int _numFrames;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"numFrames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int numFrames
    {
      get { return _numFrames; }
      set { _numFrames = value; }
    }
    private int _startFrame;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"startFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startFrame
    {
      get { return _startFrame; }
      set { _startFrame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AnimationLayer")]
  public partial class AnimationLayer : global::ProtoBuf.IExtensible
  {
    public AnimationLayer() {}
    
    private readonly global::System.Collections.Generic.List<swellanimations.Vector> _layerPoints = new global::System.Collections.Generic.List<swellanimations.Vector>();
    [global::ProtoBuf.ProtoMember(1, Name=@"layerPoints", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<swellanimations.Vector> layerPoints
    {
      get { return _layerPoints; }
    }
  
    private int _numFrames;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"numFrames", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int numFrames
    {
      get { return _numFrames; }
      set { _numFrames = value; }
    }
    private int _startFrame;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"startFrame", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startFrame
    {
      get { return _startFrame; }
      set { _startFrame = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}